//! Production [`ThrottleClient`] that calls `miner_setMaxDASize` via jsonrpsee.

use alloy_primitives::U64;
use base_batcher_core::ThrottleClient;
use futures::{StreamExt, future::BoxFuture, stream::FuturesUnordered};
use jsonrpsee::{
    http_client::{HttpClient, HttpClientBuilder},
    proc_macros::rpc,
};

/// Client-side jsonrpsee trait for the miner API extension.
#[rpc(client, namespace = "miner")]
trait MinerApiExt {
    /// Sets the maximum data availability size of any tx allowed in a block, and the total max l1
    /// data size of the block. 0 means no maximum.
    #[method(name = "setMaxDASize")]
    async fn set_max_da_size(&self, max_tx_size: U64, max_block_size: U64) -> RpcResult<bool>;
}

/// Role tag for a throttle endpoint.
///
/// Distinguishes the load-bearing primary endpoints (the sequencer(s) that
/// will actually mine blocks under the new limits) from auxiliary builder
/// endpoints (e.g. rollup-boost). The fan-out succeeds only when at least
/// one [`Sequencer`](EndpointRole::Sequencer) endpoint accepts the call —
/// builder-only acceptance is reported as an error so operators don't
/// believe throttling is in effect when the sequencer never received it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EndpointRole {
    /// A primary L2 RPC (sequencer). Acceptance here is required for the
    /// throttle to be considered effective.
    Sequencer,
    /// An additional builder endpoint (e.g. rollup-boost). Receives the
    /// fan-out for parity but is not load-bearing on its own.
    Builder,
}

impl std::fmt::Display for EndpointRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Sequencer => f.write_str("sequencer"),
            Self::Builder => f.write_str("builder"),
        }
    }
}

/// Production [`ThrottleClient`] that calls `miner_setMaxDASize` on an L2
/// execution node via a typed jsonrpsee client generated by `#[rpc(client)]`.
///
/// Connects to the standard (unauthenticated) HTTP RPC port. The `miner`
/// namespace must be enabled on the target node (`--http.api=...,miner`).
///
/// Holds one `HttpClient` per configured endpoint, each tagged with an
/// [`EndpointRole`]. On every call, the request is fanned out to all
/// endpoints in parallel — matching op-batcher's behaviour where the
/// throttle signal must reach the sequencer *and* every builder at once.
/// The call succeeds when at least one **sequencer** endpoint accepts the
/// limits; builder-only acceptance is reported as an error so the operator
/// knows the load-bearing endpoint missed the signal.
#[derive(Debug)]
pub struct RpcThrottleClient {
    /// Per-endpoint clients. Order is preserved for predictable log output.
    clients: Vec<EndpointClient>,
}

#[derive(Debug)]
struct EndpointClient {
    /// The original URL, retained for log lines so operators can identify
    /// which endpoint failed without indexing into the list externally.
    url: String,
    role: EndpointRole,
    client: HttpClient,
}

impl RpcThrottleClient {
    /// Build an [`RpcThrottleClient`] targeting one or more `(url, role)` pairs.
    ///
    /// Each URL produces an underlying `HttpClient`. The list must contain at
    /// least one [`Sequencer`](EndpointRole::Sequencer) endpoint — a fan-out
    /// to builders only would have no load-bearing target and is rejected at
    /// construction time.
    pub fn new(endpoints: &[(impl AsRef<str>, EndpointRole)]) -> eyre::Result<Self> {
        if endpoints.is_empty() {
            eyre::bail!("RpcThrottleClient requires at least one endpoint");
        }
        if !endpoints.iter().any(|(_, role)| *role == EndpointRole::Sequencer) {
            eyre::bail!(
                "RpcThrottleClient requires at least one Sequencer endpoint; \
                 a builder-only fan-out has no load-bearing target"
            );
        }
        let clients = endpoints
            .iter()
            .map(|(url, role)| {
                let url = url.as_ref();
                HttpClientBuilder::default()
                    .build(url)
                    .map(|client| EndpointClient { url: url.to_string(), role: *role, client })
                    .map_err(|e| eyre::eyre!("failed to build throttle client for {url}: {e}"))
            })
            .collect::<eyre::Result<Vec<_>>>()?;
        Ok(Self { clients })
    }

    /// Number of endpoints the client will fan out to.
    pub const fn endpoint_count(&self) -> usize {
        self.clients.len()
    }

    /// Number of endpoints tagged [`Sequencer`](EndpointRole::Sequencer).
    pub fn sequencer_count(&self) -> usize {
        self.clients.iter().filter(|e| e.role == EndpointRole::Sequencer).count()
    }
}

impl ThrottleClient for RpcThrottleClient {
    fn set_max_da_size(
        &self,
        max_tx_size: u64,
        max_block_size: u64,
    ) -> BoxFuture<'_, Result<(), Box<dyn std::error::Error + Send + Sync>>> {
        Box::pin(async move {
            let tx = U64::from(max_tx_size);
            let block = U64::from(max_block_size);

            let mut tasks: FuturesUnordered<_> = self
                .clients
                .iter()
                .map(|endpoint| async move {
                    let result = endpoint.client.set_max_da_size(tx, block).await;
                    (endpoint.url.as_str(), endpoint.role, result)
                })
                .collect();

            let total = tasks.len();
            let mut sequencer_ok = 0usize;
            let mut builder_ok = 0usize;
            let mut rejected = 0usize;
            let mut errors: Vec<String> = Vec::new();

            while let Some((url, role, result)) = tasks.next().await {
                match result {
                    Ok(true) => match role {
                        EndpointRole::Sequencer => sequencer_ok += 1,
                        EndpointRole::Builder => builder_ok += 1,
                    },
                    Ok(false) => {
                        rejected += 1;
                        tracing::warn!(
                            url = %url,
                            role = %role,
                            "miner_setMaxDASize returned false on endpoint"
                        );
                    }
                    Err(e) => {
                        tracing::warn!(
                            url = %url,
                            role = %role,
                            error = %e,
                            "throttle endpoint failed during fan-out"
                        );
                        // Cap collected error detail to avoid unbounded strings
                        // from verbose RPC errors across many endpoints.
                        if errors.len() < 10 {
                            errors.push(format!("{role} {url}: {e}"));
                        }
                    }
                }
            }
            let errored = errors.len();

            #[cfg(feature = "metrics")]
            {
                metrics::counter!(
                    "batcher_throttle_fanout_total",
                    "outcome" => "sequencer_accepted",
                )
                .increment(sequencer_ok as u64);
                metrics::counter!(
                    "batcher_throttle_fanout_total",
                    "outcome" => "builder_accepted",
                )
                .increment(builder_ok as u64);
                metrics::counter!("batcher_throttle_fanout_total", "outcome" => "rejected")
                    .increment(rejected as u64);
                metrics::counter!("batcher_throttle_fanout_total", "outcome" => "errored")
                    .increment(errored as u64);
            }

            if sequencer_ok == 0 {
                let detail = if errors.is_empty() {
                    "no transport errors".to_string()
                } else {
                    errors.join("; ")
                };
                return Err(format!(
                    "no sequencer endpoint accepted miner_setMaxDASize across {total} \
                     endpoints (sequencer_ok: 0, builder_ok: {builder_ok}, rejected: \
                     {rejected}, errored: {errored}); errors: [{detail}]"
                )
                .into());
            }
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use httpmock::prelude::*;

    use super::*;

    fn json_rpc_response(result: &str) -> String {
        format!(r#"{{"jsonrpc":"2.0","id":0,"result":{result}}}"#)
    }

    fn seq(url: impl AsRef<str>) -> (String, EndpointRole) {
        (url.as_ref().to_string(), EndpointRole::Sequencer)
    }

    fn builder(url: impl AsRef<str>) -> (String, EndpointRole) {
        (url.as_ref().to_string(), EndpointRole::Builder)
    }

    #[tokio::test]
    async fn set_max_da_size_sends_correct_request() {
        let server = MockServer::start_async().await;
        let mock = server
            .mock_async(|when, then| {
                when.method(POST)
                    .path("/")
                    .json_body_includes(r#"{"method":"miner_setMaxDASize"}"#);
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;

        let client = RpcThrottleClient::new(&[seq(server.url("/"))]).unwrap();
        client.set_max_da_size(150, 20_000).await.unwrap();
        mock.assert_async().await;
    }

    #[tokio::test]
    async fn set_max_da_size_false_return_is_error() {
        let server = MockServer::start_async().await;
        server
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("false"));
            })
            .await;

        let client = RpcThrottleClient::new(&[seq(server.url("/"))]).unwrap();
        assert!(
            client.set_max_da_size(150, 20_000).await.is_err(),
            "false response must be treated as an error"
        );
    }

    #[tokio::test]
    async fn set_max_da_size_transport_error_propagates() {
        // Port 1 has no listener — connection will fail.
        let client = RpcThrottleClient::new(&[seq("http://127.0.0.1:1")]).unwrap();
        assert!(
            client.set_max_da_size(150, 20_000).await.is_err(),
            "connection failure must propagate as error"
        );
    }

    #[tokio::test]
    async fn set_max_da_size_succeeds_when_one_of_two_responds() {
        // First sequencer endpoint refuses connections; second sequencer accepts.
        // Fan-out: one sequencer success is enough.
        let server = MockServer::start_async().await;
        server
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;

        let client =
            RpcThrottleClient::new(&[seq("http://127.0.0.1:1"), seq(server.url("/"))]).unwrap();
        client
            .set_max_da_size(150, 20_000)
            .await
            .expect("at least one sequencer accepted the limits");
    }

    #[tokio::test]
    async fn set_max_da_size_all_endpoints_fail() {
        let client =
            RpcThrottleClient::new(&[seq("http://127.0.0.1:1"), seq("http://127.0.0.1:2")])
                .unwrap();
        let err = client.set_max_da_size(150, 20_000).await.unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("no sequencer endpoint accepted"),
            "error must explain the sequencer constraint, got: {msg}"
        );
        assert!(msg.contains("errored: 2"), "error must report transport errors, got: {msg}");
    }

    #[tokio::test]
    async fn set_max_da_size_fans_out_to_all_endpoints() {
        // Two healthy endpoints — both must receive the call.
        let server_a = MockServer::start_async().await;
        let server_b = MockServer::start_async().await;
        let mock_a = server_a
            .mock_async(|when, then| {
                when.method(POST)
                    .path("/")
                    .json_body_includes(r#"{"method":"miner_setMaxDASize"}"#);
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;
        let mock_b = server_b
            .mock_async(|when, then| {
                when.method(POST)
                    .path("/")
                    .json_body_includes(r#"{"method":"miner_setMaxDASize"}"#);
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;

        let client =
            RpcThrottleClient::new(&[seq(server_a.url("/")), builder(server_b.url("/"))]).unwrap();
        client.set_max_da_size(150, 20_000).await.expect("sequencer accepts");

        mock_a.assert_async().await;
        mock_b.assert_async().await;
    }

    /// Fan-out must wait for ALL endpoints, not return on first success — a
    /// "first success short-circuits" regression would silently break parity
    /// with op-batcher's send-to-every-builder model.
    #[tokio::test]
    async fn set_max_da_size_waits_for_all_endpoints() {
        let server_fast = MockServer::start_async().await;
        let server_slow = MockServer::start_async().await;
        server_fast
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;
        let mock_slow = server_slow
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .delay(std::time::Duration::from_millis(200))
                    .body(json_rpc_response("true"));
            })
            .await;

        let client =
            RpcThrottleClient::new(&[seq(server_fast.url("/")), builder(server_slow.url("/"))])
                .unwrap();

        let start = std::time::Instant::now();
        client.set_max_da_size(150, 20_000).await.expect("both endpoints accept");
        let elapsed = start.elapsed();

        // The call must wait for the slow builder before returning. The slow
        // mock delays 200ms; require >= 150ms to prove fan-out didn't return
        // after the fast sequencer alone, while leaving 50ms of slack for CI
        // GC pauses and scheduler jitter.
        assert!(
            elapsed >= std::time::Duration::from_millis(150),
            "fan-out returned in {elapsed:?}; must wait for slow endpoint (~200ms)"
        );
        mock_slow.assert_async().await;
    }

    #[tokio::test]
    async fn set_max_da_size_partial_false_still_succeeds() {
        // One sequencer returns true, one builder returns false. The
        // sequencer accepted, so the overall call succeeds.
        let server_ok = MockServer::start_async().await;
        let server_reject = MockServer::start_async().await;
        server_ok
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;
        server_reject
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("false"));
            })
            .await;

        let client =
            RpcThrottleClient::new(&[seq(server_ok.url("/")), builder(server_reject.url("/"))])
                .unwrap();
        client.set_max_da_size(150, 20_000).await.expect("sequencer accepted");
    }

    /// Builder accepts but every sequencer fails — must surface as an error,
    /// because the load-bearing endpoint never received the limits.
    #[tokio::test]
    async fn set_max_da_size_builder_only_acceptance_is_error() {
        let server_seq_dead = MockServer::start_async().await;
        let server_builder_ok = MockServer::start_async().await;
        server_seq_dead
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(500).body("sequencer down");
            })
            .await;
        server_builder_ok
            .mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("true"));
            })
            .await;

        let client = RpcThrottleClient::new(&[
            seq(server_seq_dead.url("/")),
            builder(server_builder_ok.url("/")),
        ])
        .unwrap();
        let err = client.set_max_da_size(150, 20_000).await.unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("no sequencer endpoint accepted") && msg.contains("builder_ok: 1"),
            "error must call out builder-only acceptance, got: {msg}"
        );
    }

    #[tokio::test]
    async fn set_max_da_size_all_false_is_error() {
        let server_a = MockServer::start_async().await;
        let server_b = MockServer::start_async().await;
        for s in [&server_a, &server_b] {
            s.mock_async(|when, then| {
                when.method(POST).path("/");
                then.status(200)
                    .header("content-type", "application/json")
                    .body(json_rpc_response("false"));
            })
            .await;
        }

        let client =
            RpcThrottleClient::new(&[seq(server_a.url("/")), seq(server_b.url("/"))]).unwrap();
        let err = client.set_max_da_size(150, 20_000).await.unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("rejected: 2"), "error must report rejection count, got: {msg}");
    }

    #[test]
    fn endpoint_count_reports_configured_endpoints() {
        let client = RpcThrottleClient::new(&[
            seq("http://a:8545"),
            seq("http://b:8545"),
            builder("http://c:8545"),
        ])
        .expect("three endpoints");
        assert_eq!(client.endpoint_count(), 3);
        assert_eq!(client.sequencer_count(), 2);
    }

    #[test]
    fn new_rejects_empty_endpoint_list() {
        let endpoints: &[(&str, EndpointRole)] = &[];
        assert!(RpcThrottleClient::new(endpoints).is_err(), "empty endpoint list must be rejected");
    }

    #[test]
    fn new_rejects_builder_only_configuration() {
        let err = RpcThrottleClient::new(&[builder("http://b1:8545"), builder("http://b2:8545")])
            .unwrap_err();
        assert!(
            err.to_string().contains("at least one Sequencer"),
            "must reject configurations with no sequencer, got: {err}"
        );
    }
}
