//! Metrics for the derivation pipeline.

base_metrics::define_metrics! {
    base_consensus_derive

    #[describe("The block height of the pipeline l1 origin")]
    pipeline_origin: gauge,

    #[describe("The latest L2 block height that the pipeline stepped on")]
    pipeline_step_block: gauge,

    #[describe("If the batch reader is set")]
    batch_reader_set: gauge,

    #[describe("The amount of time it takes to advance the pipeline origin")]
    pipeline_origin_advance: histogram,

    #[describe("The time it takes to update the system config")]
    system_config_update: histogram,

    #[describe("The number of frames in the frame queue")]
    frame_queue_buffer: gauge,

    #[describe("The memory size of frames held in the frame queue")]
    frame_queue_mem: gauge,

    #[describe("The number of channels in the channel assembler stage")]
    channel_buffer: gauge,

    #[describe("The memory size of channels held in the channel assembler stage")]
    channel_mem: gauge,

    #[describe("The number of blocks until the next channel times out")]
    blocks_until_channel_timeout: gauge,

    #[describe("The maximum rlp byte size of a channel")]
    max_rlp_bytes: gauge,

    #[describe("The number of batches held in the batch stream stage")]
    batch_buffer: gauge,

    #[describe("The memory size of batches held in the batch stream stage")]
    batch_mem: gauge,

    #[describe("The read batches")]
    #[label("type", batch_type)]
    read_batches: counter,

    #[describe("The total number of pipeline steps on the derivation pipeline")]
    pipeline_steps: gauge,

    #[describe("The total number of prepared attributes generated by the derivation pipeline")]
    prepared_attributes: gauge,

    #[describe("Number of times the pipeline has been signalled")]
    #[label("type", signal_type)]
    pipeline_signals: gauge,

    #[describe("Earliest l1 blocks height")]
    l1_blocks_start: gauge,

    #[describe("Latest l1 blocks height")]
    l1_blocks_end: gauge,

    #[describe("The number of payload attributes in the current span")]
    span_size: gauge,

    #[describe("The number of transactions in the latest derived payload attributes")]
    payload_tx_count: gauge,

    #[describe("The source of pipeline data")]
    #[label("source", source)]
    dap_sources: gauge,

    #[describe("The validity of the batch being processed")]
    #[label("validity", validity)]
    batch_validity: counter,

    #[describe("The time it takes to validate a span batch")]
    check_batch_prefix_duration: histogram,

    #[describe("The time it takes to build payload attributes")]
    attributes_build_duration: histogram,

    #[describe("The number of payload attributes buffered in the pipeline")]
    payload_attributes_buffer: gauge,

    #[describe("The latest decompressed batch size")]
    latest_decompressed_batch_size: gauge,

    #[describe("The latest decompressed batch type")]
    latest_decompressed_batch_type: gauge,
}

base_metrics::define_metrics_named! {
    GenesisMetrics, "base_consensus_genesis",

    #[describe("The latest block number for a system config update")]
    latest_system_config_update: gauge,

    #[describe("The block height at which a system config update errored")]
    sys_config_update_error: gauge,
}
